language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - nightly

env:
  - PYTHON=""

jobs:
  allow_failures:
    - julia: nightly
    - os: windows
    - stage: "Documentation"
  fast_finish: true
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --color=yes --project=. -e 'using Pkg; Pkg.instantiate()'
        - julia --color=yes --project=. docs/make.jl
      after_success: skip

notifications:
  email: false

codecov: true
coveralls: true
