language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - nightly

env:
  - PYTHON=""

matrix:
  allow_failures:
    - julia: nightly
    - os: windows
  fast_finish: true

after_script:
  - bash ./docs/travis.sh

notifications:
  email: false

codecov: true
coveralls: true
