language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.3
  - 1.4
  - 1.5
  - nightly

env:
  - PYTHON=""

jobs:
  allow_failures:
    - julia: 1.4
    - julia: 1.5
    - julia: nightly
  fast_finish: true

notifications:
  email: false

codecov: true
coveralls: true

script:
  - travis_wait 30 julia --project --color=yes -e 'using Pkg; Pkg.add("PyCall"); Pkg.build("PyCall"; verbose=true); Pkg.test(coverage=true)';

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';
